[2025-01-05T09:53:18.305+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.sql_start_to_log scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-05T09:53:18.312+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.sql_start_to_log scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-05T09:53:18.313+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-01-05T09:53:18.485+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): sql_start_to_log> on 2025-01-04 00:00:00+00:00
[2025-01-05T09:53:18.491+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: insert_data.sql_start_to_log scheduled__2025-01-04T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-01-05T09:53:18.491+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: insert_data.sql_start_to_log scheduled__2025-01-04T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-01-05T09:53:18.491+0000] {standard_task_runner.py:60} INFO - Started process 76 to run task
[2025-01-05T09:53:18.493+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-01-05T09:53:18.495+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'sql_start_to_log', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpajgqjaa6']
[2025-01-05T09:53:18.499+0000] {standard_task_runner.py:88} INFO - Job 343: Subtask sql_start_to_log
[2025-01-05T09:53:18.501+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: insert_data.sql_start_to_log scheduled__2025-01-04T00:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2025-01-05T09:53:18.502+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: insert_data.sql_start_to_log scheduled__2025-01-04T00:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2025-01-05T09:53:18.504+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-01-05T09:53:18.541+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.sql_start_to_log scheduled__2025-01-04T00:00:00+00:00 [running]> on host 403e7aadd7ee
[2025-01-05T09:53:18.605+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='agushchin' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='sql_start_to_log' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-01-05T09:53:18.606+0000] {sql.py:276} INFO - Executing: INSERT INTO logs.log_details ("time", run_id, job) 
		VALUES (CURRENT_TIMESTAMP, 'scheduled__2025-01-04T00:00:00+00:00','Starting job');
[2025-01-05T09:53:18.614+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-05T09:53:18.620+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-05T09:53:18.632+0000] {sql.py:450} INFO - Running statement: INSERT INTO logs.log_details ("time", run_id, job) 
		VALUES (CURRENT_TIMESTAMP, 'scheduled__2025-01-04T00:00:00+00:00','Starting job');, parameters: None
[2025-01-05T09:53:18.636+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-05T09:53:18.646+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=sql_start_to_log, execution_date=20250104T000000, start_date=20250105T095318, end_date=20250105T095318
[2025-01-05T09:53:18.668+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-05T09:53:18.694+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
