[2025-01-11T08:42:44.758+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: insert_data.md_currency_d scheduled__2025-01-10T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
